### ISSUE TITLE
switch license to MIT or ruby ?

### ISSUE THREAD

**Issue by grosser** [flori/term-ansicolor#24]
I'm combing through our gems to find GPL stuff that worries our lawyers, would it be possible to switch to MIT or BSD or Apache-v2 or LGPL ? or to release under GPL-v2 and xyz

@flori

**Comment by ypresto** [comment]
This library enforces other libraries depends on it to be released under GPL.
This means all libraries in below link are violating GPL.

https://github.com/search?utf8=%E2%9C%93&q=%22license+mit%22+%22s.add_dependency+%27term-ansicolor%27%22+language%3ARuby&type=Code

It's just nightmare...
For example if rails want to depend on this library, they should change license of all their dependent code to GPL.
So I prefer LGPL for library, it brings best balance between copyleft and usability. :)

**Comment by flori** [comment]
> This library enforces other libraries depends on it to be released under GPL.

Prove it. Show me how any of that violates the GPL. I sure you read the license text, didn't you?

> LGPL

How do you even link an executable dynamically or statically to this ruby library? I hope you are aware of the fact that this was the sole reason the LGPL was created.

**Comment by ypresto** [comment]
FYI:
There is MIT licensed alternative: https://github.com/sickill/rainbow
Anyone having issue of GPL would switch to it..!

----

GPL is not limited to just "linking", as FAQ says.

> We believe that a proper criterion depends both on the mechanism of communication (exec, pipes, rpc, function calls within a shared address space, etc.) and the semantics of the communication (what kinds of information are interchanged).

https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

Dependent libraries "calls function" of this library (and it is not just passing arguments to another command) so it can be determined "linked" legally.

Found answer in ruby forum (but no evidence).
https://www.ruby-forum.com/topic/4404829

**Comment by ypresto** [comment]
It is ambiguous part, as FAQ says:

> This is a legal question, which ultimately judges will decide.

So it cannot prove by us. Only judges can.
But it is too risky to use library with potential lawsuit without consulting lawyer.So I'll switch to other library (by sending PR to library depends on this).

**Comment by flori** [comment]
> GPL is not limited to just "linking", as FAQ says.

This was my reply to your suggestion of the LGPL. Why did you reply and delete this context?

**Comment by flori** [comment]
> Anyone having issue of GPL would switch to it..!

Please, you still have to show how having

    s.add_dependency  "term-ansicolor", "~> 1.2.2"

in your spec file violates the GPL. Do you always comment on other peoples' free software projects and spread FUD? Humour me, will you?

**Comment by ypresto** [comment]
No, I think spec file is not matter, actually.
Calling `Term::ANSIColor.foobar` can be decided as "linking" legally as FAQ.

**Comment by flori** [comment]
> No, I think spec file is not matter, actually.

So you were wrong about this?

> Calling Term::ANSIColor.foobar can be decided as "linking" legally as FAQ.

So how do you call a function of this library from a program you distribute without distributing the source code of the library?

**Comment by ypresto** [comment]
> So you were wrong about this?

Yes it was ambiguous about "linking" in search link. 

> So how do you call a function of this library from a program you distribute without distributing the source code of the library?

You meant "distribute without GPL library" does not violates GPL.
But it is different from FAQ's interpretation.

Just "linking" to GPL software enforces linking software to be released in GPL:
https://www.gnu.org/licenses/gpl-faq.en.html#LinkingWithGPL

And even it is only "linking" that does not contains link target in distribution, e.g. Linux:
https://www.gnu.org/licenses/gpl-faq.en.html#NonfreeDriverKernelLinux

So, to "link" with GPL incompatible software exception statement is necessary in license of link target, as FAQ says.
https://www.gnu.org/licenses/gpl-faq.en.html#LinkingOverControlledInterface

Also, there is mention to JavaScript function call from HTML in FAQ and it counts as "linking", so Ruby function call can be also considered as "linking":
https://www.gnu.org/licenses/gpl-faq.en.html#WMS

**Comment by flori** [comment]
> https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

> Dependent libraries "calls function" of this library (and it is not just passing arguments to another command) so it can be determined "linked" legally.

According to this link only statically and dynamically linked libraries are considered definite cases of combination:

    If the modules are included in the same executable file, they are definitely combined in
    one program. If modules are designed to run linked together in a shared address space,
    that almost surely means combining them into one program.

And this is definitely not the case either:

    But if the semantics of the communication are intimate enough, exchanging complex internal
    data structures, that too could be a basis to consider the two parts as combined into a larger  program.

> Found answer in ruby forum (but no evidence).
> https://www.ruby-forum.com/topic/4404829

Which answer is that? It certainly doesn't show that calling a ruby function is akin to linking to a shared library.

**Comment by glebm** [comment]
Regardless, I think this applies:

> If the modules are included in the same executable file, they are definitely combined in one program. 

E.g. my rather popular `i18n-tasks` tool includes Term::AnsiColor from its executable, which as I understand we need to stop doing and switch to another library.

**Comment by flori** [comment]
> E.g. my rather popular i18n-tasks tool includes Term::AnsiColor from its executable, which as I understand we need to stop doing and switch to another library.

No, this means that the library is statically linked into an executable file, the thing that is output as `gcc -o executable`. You have to use `gcc -static` to link statically. You cannot do this in ruby, the ruby interpreter doesn't statically (or dynamically) link to the ruby library files, but only dynamically to c-extensions.

**Comment by glebm** [comment]
The license does not seem to say that. An "executable file" is just a file with `+x`.

Another excerpt, while not exactly on point, but seems to confirm that dynamic or static linking is meant in-spirit and not as per C definition:

> For instance, Perl comes with many Perl modules, and a Java implementation comes with many Java classes. These libraries and the programs that call them are always dynamically linked together.
