### ISSUE TITLE
No info for v1.3.1

### ISSUE THREAD

**Issue by saizai** [flori/term-ansicolor#26]
@flori Looks like you pushed the gem, but didn't update the repo or changelog. Could you please do so?

Thanks!

**Comment by domcleal** [comment]
Yeah, I'm also interested in this, in particular why a required_rubygems_version was set at` >= 1.9` (it's `>= 0` in this repo) and why binaries were renamed in a patch release.

**Comment by flori** [comment]
which binaries were renamed in a patch release?

**Comment by domcleal** [comment]
<pre>
  DIFFERENT files:
    1.3.0->1.3.1:
      * Deleted:
            bin/cdiff
            bin/colortab
            bin/decolor
      * Added:
            bin/term_cdiff
            bin/term_colortab
            bin/term_decolor
</pre>

Not my biggest worry though, but unfortunately the minimum rubygems runtime version is causing me a few problems on older OSes.  Would you mind pushing your local repo to here so we can see what's changed easily?

**Comment by flori** [comment]
Oops, this branch wasn't supposed to be released yet at all. I just release this fix as v1.3.2:

Can you check it out?

**Comment by domcleal** [comment]
Much better, looks and seems to work fine again.  Thanks for the fast fix @flori.

**Comment by markgandolfo** [comment]
:( for yanking...

**Comment by deivid-rodriguez** [comment]
Yes... too bad :(

**Comment by rogierslag** [comment]
Yanking also meant we had to update all of our appservers to a newer version of the gem just so we could install another server. I think in this case it was not really required to yank it (maybe there were internal reasons to do so, but from this thread I think a new version would suffice)

**Comment by saizai** [comment]
A new version was in fact pushed.

From my git commit:

    rename vendor/cache/{term-ansicolor-1.3.0.gem =>
term-ansicolor-1.3.2.gem} (70%)

**Comment by rogierslag** [comment]
yup, but `Gemfile.lock` doesnt agree on that. So in that case users all have to push an updated app version with the correct dependency to allow for redeployment
