### ISSUE TITLE
Lock tins to 1.6.0 on Ruby 1.9

### ISSUE THREAD

**Issue by louisajaca** [flori/term-ansicolor#28]
We're having trouble on our build when term-ansicolor is being bundled updated. We've locked it to 1.3.0 but it's still getting the updated tins version.

Gem::InstallError: tins requires Ruby version >= 2.0.
An error occurred while installing tins (1.8.1), and Bundler cannot continue.
Make sure that `gem install tins -v '1.8.1'` succeeds before bundling.

@flori Can you lock tins to ~> 1.6.0 on Ruby 1.9? Similar to what rails_admin did? https://github.com/sferik/rails_admin/issues/2464

Thanks!

**Comment by gorn** [comment]
Would be great to contribute 1.9 compatibility to tins, or give up this dependency, see
flori/tins#15
