### ISSUE TITLE
Term is quite common name, why not use AnsiTerm, or something like that?

### ISSUE THREAD

**Issue by ifesdjeen** [flori/term-ansicolor#3]
Actually, the work Term is widely used to determine translaiton, terms, tags. Especially for models in Web applications.

You know that term-ansicolor is used in Cucumber. So, people who're using cucumber can't name their model Term for now. They should fork both repositories to make it happen.

Is that possible at all?
Thank you!

**Comment by michaelbrawn** [comment]
Reopening https://github.com/flori/term-ansicolor/issues/36
