### ISSUE TITLE
Inclusion of the `protocol` gem via the `mize` gem causing method name conflicts for the `Object#protocol` method

### ISSUE THREAD

**Issue by dark-panda** [flori/term-ansicolor#40]
We noticed that we have code erroring out in our app recently involving some checking around method names in a `respond_to_missing?` handler we have and the method name it's coming up with is `protocol`, which is defined as a monkey patch to `Object` at https://github.com/flori/protocol/blob/4fb1ca24790c0f140aeb99b40fab5a63de3c032d/lib/protocol/xt.rb#L27. 

Would it perhaps be safer to alias this method to something less likely to clash with other common method names, like perhaps `__protocol__` or something?

**Comment by flori** [comment]
Can you check `term-ansicolor 1.10.4` or later?
